metrics:
  - system

dataset: LibriCSS
paths:
  root: LibriCSS
  manifest: LibriCSS/test/manifest.csv
  raw_dataset_name: LibriCSS
split: test

sample_rate: 16000
max_items: null
overwrite: false
save_audio_outputs: true
save_audio_num_samples: 20
save_audio_seed: 2024
whisper_model: large-v3-turbo
dnsmos_num_threads: 1

compressor:
  sources:
    - s1
    - s2

extractor:
  checkpoint_path: null
  num_infer_steps: 50
  eta: 0.0
  seed: 2024
  decode_std: mixture

corrector:
  checkpoint_path: null
  reverse_starting_point: 0.5
  num_steps: 1
